package com.dengage.rnexample


object Constants {

  const val FIREBASE_APP_INTEGRATION_KEY = "GH_p_l__s_l_zkKfXP9PQguU6s0MYA0yCpONf5gB_s_l_WOh4cio2eoMR3_s_l_qJzuETWcNi2wQ_p_l_gsFWN6x6MdWgtAzE6IjEsWMthsxqiJvPiVocCylL_s_l_XUCCDcRyJYLBphkiwGg6dPYOkeVdZFn16rDW9OXIHQvmlxBg_e_q__e_q_"

  const val HUAWEI_APP_INTEGRATION_KEY = "HUAWEI_APP_INTEGRATION_KEY"
}
